name: Deploy static sites

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-principal:
    name: Deploy principal
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload principal
        uses: SamKirkland/FTP-Deploy-Action@v4.4.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./principal/
          server-dir: ./
          exclude: |
            **/.git*
            **/.git*/**
            **/.github/**
            **/node_modules/**
            diabetes/**
            checkup/**
            emagrecimento/**

  deploy-diabetes:
    name: Deploy diabetes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload diabetes
        uses: SamKirkland/FTP-Deploy-Action@v4.4.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./diabetes/
          server-dir: ./diabetes/
          exclude: |
            **/.git*
            **/.git*/**
            **/.github/**
            **/node_modules/**

  deploy-checkup:
    name: Deploy checkup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload checkup
        uses: SamKirkland/FTP-Deploy-Action@v4.4.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./checkup/
          server-dir: ./checkup/
          exclude: |
            **/.git*
            **/.git*/**
            **/.github/**
            **/node_modules/**

  deploy-emagrecimento:
    name: Deploy emagrecimento
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload emagrecimento
        uses: SamKirkland/FTP-Deploy-Action@v4.4.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./emagrecimento/
          server-dir: ./emagrecimento/
          exclude: |
            **/.git*
            **/.git*/**
            **/.github/**
            **/node_modules/**
